# -*- coding: utf-8 -*-
"""
Created on Mon Mar 19 18:06:59 2018

@author: DrDave
"""

#Set Joystick Index and Buttons here:
CANNON_JOYSTICK = 0
CANNON_BUTTON   = 0

MG_JOYSTICK     = 0
MG_BUTTON       = 2

#ROCKET_JOYSTICK = 0
#ROCKET_BUTTON   = 3

#BOMB_JOYSTICK = 0
#BOMB_BUTTON   = 1


YAK7_NAME = 'Yak 7'
YAK7_CANNON_DURATION = 8.65
YAK7_CANNON_NAME = 'Sh'
YAK7_MG_DURATION     = 15.10
YAK7_MG_NAME = 'UB'


YAK1B_NAME = 'Yak 1b Ser. 127'
YAK1B_CANNON_DURATION = 10.1
YAK1B_CANNON_NAME = 'Sh'
YAK1B_MG_DURATION     = 14.2
YAK1B_MG_NAME = 'UB'

YAK69_NAME = 'Yak Ser. 69'
YAK69_CANNON_DURATION = 8.2
YAK69_CANNON_NAME = 'ShKAS'
YAK69_MG_DURATION     = 25.4
YAK69_MG_NAME = 'ShVAK'

LAGG_23mm_NAME = 'Lagg-3'
LAGG_CANNON_DURATION = 8.50
LAGG_CANNON_NAME = 'Y23'
LAGG_MG_DURATION     = 13.1
LAGG_MG_NAME = 'UB_'

MIG3_BS_NAME = 'Mig-3'
MIG3_CANNON_DURATION = 0
MIG3_CANNON_NAME = ''
MIG3_MG_DURATION     = 20.5
MIG3_MG_NAME = 'BS 12.7mm (700 Rounds)'

GUN_FORMAT   = '{0:<20}'
PLANE_FORMAT = '{0:<32}'

PLANE_DICT = {
'YAK1B':
{'name':PLANE_FORMAT.format(YAK1B_NAME), 'mgDuration':YAK1B_MG_DURATION, 'cannonDuration':YAK1B_CANNON_DURATION,'mgName':GUN_FORMAT.format(YAK1B_MG_NAME),'cannonName':GUN_FORMAT.format(YAK1B_CANNON_NAME)},
'LAGG3_23':{'name':PLANE_FORMAT.format(LAGG_23mm_NAME),'mgDuration':LAGG_MG_DURATION,'cannonDuration':LAGG_CANNON_DURATION,'mgName':GUN_FORMAT.format(LAGG_MG_NAME),'cannonName':GUN_FORMAT.format(LAGG_CANNON_NAME)},
'MIG3-BS700':
{'name':PLANE_FORMAT.format(MIG3_BS_NAME),'mgDuration':MIG3_MG_DURATION,'mgName':GUN_FORMAT.format(MIG3_MG_NAME)},
'YAK69':
{'name':PLANE_FORMAT.format(YAK69_NAME),'mgDuration':YAK69_MG_DURATION,'cannonDuration':YAK69_CANNON_DURATION,'mgName':GUN_FORMAT.format(YAK69_MG_NAME),'cannonName':GUN_FORMAT.format(YAK69_CANNON_NAME)}, 
'YAK7':
{'name':PLANE_FORMAT.format(YAK7_NAME),'mgDuration':YAK7_MG_DURATION,'cannonDuration':YAK7_CANNON_DURATION,'mgName':GUN_FORMAT.format(YAK7_MG_NAME),'cannonName':GUN_FORMAT.format(YAK7_CANNON_NAME)}
}
